const API_URL='https://script.google.com/macros/s/AKfycbybR7jEON3G-v20sq_VTLkr7E_5SSAUPcKDqjFYorMfoinnu70LOiO26IcEXz0uK8E/exec';
const LOCAL_PREVIEW=['127.0.0.1','localhost'].includes(location.hostname)&&!new URLSearchParams(location.search).has('live');
const LEVELS=[{name:'Perlu Penambahbaikan',range:[1,5],color:'#ef5d64'},{name:'Memuaskan',range:[6,10],color:'#f5a20b'},{name:'Baik',range:[11,15],color:'#3f7fea'},{name:'Cemerlang',range:[16,20],color:'#12b886'}];
const RUBRIC=[
 {key:'content',title:'Kandungan & Kaitan Tema',short:'Kandungan',descriptions:['Kandungan sangat terhad dan kurang jelas; kaitan tema, masalah dan objektif tidak dinyatakan dengan jelas.','Kandungan asas dikenal pasti tetapi maklumat penting masih kurang lengkap dan kaitan tema agak jelas.','Kandungan jelas, lengkap dan relevan; masalah, objektif serta idea inovasi dinyatakan dengan baik.','Kandungan sangat lengkap, jelas dan sangat relevan; idea, masalah, objektif dan penyelesaian disampaikan secara menyeluruh.']},
 {key:'design',title:'Reka Bentuk & Kreativiti',short:'Reka Bentuk',descriptions:['Reka bentuk kurang menarik dan kurang tersusun; warna, font dan grafik tidak konsisten.','Reka bentuk agak menarik tetapi masih mempunyai kelemahan susun atur atau elemen visual.','Reka bentuk menarik, kemas dan kreatif dengan penggunaan visual yang konsisten.','Reka bentuk sangat menarik, kreatif dan profesional dengan identiti visual yang kuat.']},
 {key:'clarity',title:'Keberkesanan & Kejelasan Maklumat',short:'Kejelasan',descriptions:['Maklumat sukar difahami dan poster tidak menerangkan inovasi dengan baik secara bersendiri.','Maklumat boleh difahami secara umum tetapi sebahagiannya kurang jelas atau kurang tersusun.','Maklumat jelas, ringkas dan tersusun; mesej mudah difahami tanpa penerangan lisan.','Maklumat sangat jelas, tepat dan berkesan dengan hierarki maklumat yang sangat baik.']},
 {key:'technical',title:'Kualiti Teknikal',short:'Teknikal',descriptions:['Kualiti teknikal rendah; imej kabur, teks sukar dibaca atau spesifikasi tidak dipatuhi.','Kualiti sederhana dengan beberapa kelemahan resolusi, teks, grafik, ejaan atau susun atur.','Imej dan grafik jelas, teks mudah dibaca serta kebanyakan spesifikasi dipatuhi.','Kualiti sangat tinggi dan profesional; grafik tajam, kemasan baik dan spesifikasi dipatuhi.']},
 {key:'impact',title:'Potensi & Impak',short:'Impak',descriptions:['Impak kurang jelas tanpa bukti kukuh tentang keberkesanan atau potensi pengembangan.','Mempunyai impak asas tetapi bukti keberkesanan dan potensi pengembangan masih terhad.','Menunjukkan impak jelas dan berpotensi digunakan serta diperluas ke peringkat lebih tinggi.','Impak sangat signifikan dan meyakinkan dengan bukti jelas serta potensi penyebarluasan tinggi.']}
];
const COLORS=['#2458e6','#1677a8','#d39a24'];
const state={judges:[],judge:null,token:sessionStorage.getItem('puice_token')||'',adminToken:sessionStorage.getItem('puice_admin_token')||'',poster:null,nextPoster:null,progress:{completed:0,total:0},scores:{},activeRubricKey:null,galleryPage:1,galleryPages:1,galleryItems:[],galleryTimer:null,refreshTimer:null,refreshing:false,saveProgressTimer:null,saveProgressValue:0,pendingRequestId:'',pendingPosterId:'',zoomScale:1,zoomX:0,zoomY:0,zoomPointers:new Map(),zoomStartDistance:0,zoomStartScale:1};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];

document.addEventListener('DOMContentLoaded',()=>{bindEvents();renderRubric();bootstrap().finally(startAutoRefresh);});

function bindEvents(){
 $('#changeJudgeBtn').addEventListener('click',changeJudge); $('#pinSubmit').addEventListener('click',login); $('#pinInput').addEventListener('keydown',e=>{if(e.key==='Enter')login();});
 $$('.tab-btn').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab))); $('#submitBtn').addEventListener('click',openConfirmation);
 $('#confirmClose').addEventListener('click',()=>$('#confirmDialog').close()); $('#confirmCancel').addEventListener('click',()=>$('#confirmDialog').close()); $('#confirmSubmit').addEventListener('click',saveScore);
 $('#openPosterBtn').addEventListener('click',()=>openPosterModal(state.poster)); $('#posterImage').addEventListener('click',()=>openPosterModal(state.poster)); $('#posterModalClose').addEventListener('click',()=>$('#posterDialog').close()); $('#retryImageBtn').addEventListener('click',loadPosterImage);bindPosterZoom();
 $('.go-gallery').addEventListener('click',()=>switchTab('gallery')); $('#gallerySearch').addEventListener('input',()=>{clearTimeout(state.galleryTimer);state.galleryTimer=setTimeout(()=>{state.galleryPage=1;loadGallery();},350);});
 $('#galleryStatus').addEventListener('change',()=>{state.galleryPage=1;loadGallery();});
 $('#galleryPrev').addEventListener('click',()=>{if(state.galleryPage>1){state.galleryPage--;loadGallery();}}); $('#galleryNext').addEventListener('click',()=>{if(state.galleryPage<state.galleryPages){state.galleryPage++;loadGallery();}});
 $('#refreshLeaderboard').addEventListener('click',loadLeaderboard);
 $('#openAdminResults').addEventListener('click',openAdminResults); $('#adminPinClose').addEventListener('click',()=>$('#adminPinDialog').close()); $('#adminPinSubmit').addEventListener('click',adminLogin); $('#adminPinInput').addEventListener('keydown',e=>{if(e.key==='Enter')adminLogin();}); $('#closeAdminResults').addEventListener('click',()=>showScreen('judge')); $('#refreshAdminResults').addEventListener('click',loadAdminLeaderboard);
}

async function api(action,payload={},usePost=false,options={}){
 if(LOCAL_PREVIEW)return await mockApi(action,payload);
 const attempts=action==='saveScore'?3:2;let lastError;
 for(let attempt=1;attempt<=attempts;attempt++){
  try{return await apiOnce(action,payload,usePost);}catch(err){lastError=err;if(!err.retryable||attempt===attempts)throw err;if(options.onRetry)options.onRetry(attempt+1);await wait(450*attempt);}
 }
 throw lastError;
}
async function apiOnce(action,payload,usePost){
 const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),25000);
 try{
  let res;if(usePost){res=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload}),signal:controller.signal});}
  else{const url=new URL(API_URL);url.searchParams.set('action',action);Object.entries(payload).forEach(([k,v])=>url.searchParams.set(k,v));res=await fetch(url,{signal:controller.signal});}
  const text=await res.text();let data;
  try{data=JSON.parse(text);}catch(parseError){const err=new Error(/^\s*</.test(text)?'Sambungan ke Google terganggu seketika.':'Respons pelayan tidak dapat dibaca.');err.retryable=true;throw err;}
  if(!res.ok){const err=new Error(data.message||'Pelayan Google tidak dapat dihubungi.');err.retryable=res.status===429||res.status>=500;throw err;}
  if(!data.ok)throw new Error(data.message||'Permintaan tidak berjaya.');return data.data;
 }catch(err){if(err.name==='AbortError'){const timeoutError=new Error('Sambungan mengambil masa terlalu lama.');timeoutError.retryable=true;throw timeoutError;}if(err instanceof TypeError){err.retryable=true;}throw err;}finally{clearTimeout(timeout);}
}

async function bootstrap(){
 try{
  setLoading('Menyemak hakim aktif dan kesiapsiagaan poster…'); const data=await api('bootstrap'); state.judges=data.judges||[]; renderJudgeCards();
  const last=localStorage.getItem('puice_last_judge'); if(state.token&&last){state.judge=state.judges.find(j=>j.id===last);if(state.judge){try{await openApp(true);return;}catch{sessionStorage.removeItem('puice_token');state.token='';}}}
  showScreen('judge');
 }catch(err){showLoadingError(err.message);}
}

function startAutoRefresh(){if(state.refreshTimer)return;state.refreshTimer=setInterval(refreshLiveState,20000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshLiveState();});window.addEventListener('focus',refreshLiveState);}
async function refreshLiveState(){if(document.hidden||state.refreshing)return;state.refreshing=true;try{if(!$('#judgeScreen').classList.contains('hidden')){const data=await api('bootstrap');state.judges=data.judges||[];renderJudgeCards();return;}if(!state.token||$('#appScreen').classList.contains('hidden')||$('#confirmDialog').open)return;const currentId=state.poster?.id||null,data=await api('dashboard',{token:state.token},true),newId=data.poster?.id||null;if(currentId!==newId){applyDashboard(data);requestAnimationFrame(scrollToCurrentPoster);}else{state.progress=data.progress||state.progress;updateProgress();}}catch{}finally{state.refreshing=false;}}

function setLoading(msg){$('#loadingMessage').textContent=msg;showScreen('loading');}
function showLoadingError(msg){$('#loadingScreen h1').textContent='Sambungan belum tersedia';$('#loadingMessage').textContent=msg;$('.loading-line').innerHTML='<button class="secondary-btn" onclick="location.reload()">Cuba Semula</button>';}
function showScreen(name){['loadingScreen','judgeScreen','appScreen','adminResultsScreen'].forEach(id=>$('#'+id).classList.add('hidden'));$('#'+name+'Screen').classList.remove('hidden');}

function renderJudgeCards(){
 $('#judgeCards').innerHTML=state.judges.map((j,i)=>{const pct=j.total?Math.round(j.completed/j.total*100):0;return `<button class="judge-card" style="--accent:${COLORS[i%COLORS.length]}" data-id="${escapeHtml(j.id)}"><span class="judge-avatar">${initials(j.name)}</span><h2>${escapeHtml(j.name)}</h2><p>Hakim ini telah menilai ${j.completed} daripada ${j.total} poster.</p><div class="mini-progress"><span style="width:${pct}%"></span></div><div class="judge-progress-row"><span>${pct}% selesai</span><strong>Teruskan →</strong></div></button>`}).join('');
 $$('.judge-card').forEach((card,i)=>card.addEventListener('click',()=>openPin(state.judges[i],COLORS[i])));
}
function openPin(judge,color){state.judge=judge;$('#pinJudgeName').textContent=judge.name;$('#pinAvatar').textContent=initials(judge.name);$('#pinAvatar').style.setProperty('--accent',color);$('#pinInput').value='';$('#pinError').textContent='';$('#pinDialog').showModal();setTimeout(()=>$('#pinInput').focus(),100);}
async function login(){const pin=$('#pinInput').value.trim();if(!/^\d{6}$/.test(pin)){return $('#pinError').textContent='Masukkan PIN enam digit yang sah.';}setButtonBusy($('#pinSubmit'),true,'Mengesahkan…');$('#pinError').textContent='';setLoading('Mengesahkan PIN dan menyediakan poster anda…');try{const data=await api('login',{judgeId:state.judge.id,pin},true);state.token=data.token;sessionStorage.setItem('puice_token',state.token);localStorage.setItem('puice_last_judge',state.judge.id);const dashboard=data.dashboard||await api('dashboard',{token:state.token},true);state.judge=dashboard.judge||data.judge;applyDashboard(dashboard);$('#headerJudgeName').textContent=state.judge.name;$('#headerAvatar').textContent=initials(state.judge.name);$('#pinDialog').close();showScreen('app');}catch(err){showScreen('judge');$('#pinError').textContent=err.message;}finally{setButtonBusy($('#pinSubmit'),false,'Sahkan & Masuk');}}
async function openApp(resuming){setLoading('Menyambung penjurian anda…');const data=await api('dashboard',{token:state.token},true);state.judge=data.judge;applyDashboard(data);$('#headerJudgeName').textContent=state.judge.name;$('#headerAvatar').textContent=initials(state.judge.name);showScreen('app');if(resuming)toast('Selamat kembali. Penjurian anda disambung.');}
function changeJudge(){sessionStorage.removeItem('puice_token');state.token='';state.judge=null;state.poster=null;renderJudgeCards();showScreen('judge');}

function applyDashboard(data){state.poster=data.poster||null;state.nextPoster=data.nextPoster||null;state.progress=data.progress||{completed:0,total:0};updateProgress();if(state.poster){state.scores={};restoreDraft();state.activeRubricKey=RUBRIC.find(r=>!state.scores[r.key])?.key||RUBRIC[0].key;renderPoster();$('#posterCard').classList.remove('hidden');$('#completionCard').classList.add('hidden');}else{$('#posterCard').classList.add('hidden');$('#completionCard').classList.remove('hidden');$('#completionSummary').textContent=`Anda telah melengkapkan ${state.progress.completed} daripada ${state.progress.total} poster. Kemas kini terakhir: ${formatDate(data.lastUpdated)}.`;}}
function updateProgress(previous){const {completed,total}=state.progress,pct=total?Math.round(completed/total*100):0;$('#progressText').textContent=`${completed} daripada ${total} poster selesai`;$('#progressPercent').textContent=`${pct}%`;$('#progressBar').style.width=`${pct}%`;let msg='Setiap poster membawa anda lebih hampir ke garisan penamat.';if(pct>=100)msg='Penjurian anda telah lengkap!';else if(pct>=75)msg='Sedikit lagi!';else if(pct>=50)msg='Separuh perjalanan selesai!';else if(pct>=25)msg='Permulaan yang hebat!';$('#milestoneText').textContent=msg;if(previous!=null)[25,50,75,100].forEach(m=>{if(previous<m&&pct>=m)confetti();});}

function renderPoster(){const p=state.poster;$('#posterId').textContent=p.id;$('#posterStatus').textContent=p.judged?'Telah dinilai':'Belum dinilai';$('#posterStatus').classList.toggle('judged',!!p.judged);$('#posterTitle').textContent=p.title;$('#posterSchool').textContent=p.school;$('#posterImage').alt=`Poster ${p.title} dari ${p.school}`;loadPosterImage();renderRubric();if(state.nextPoster?.imageUrl){const img=new Image();img.src=state.nextPoster.imageUrl;}}
function scrollToCurrentPoster(){const target=state.poster?$('#posterCard'):$('#completionCard');if(!target)return;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;target.scrollIntoView({behavior:reduced?'auto':'smooth',block:'start'});}
function loadPosterImage(){const img=$('#posterImage');img.classList.add('hidden');$('#imageError').classList.add('hidden');$('#imageSkeleton').classList.remove('hidden');img.onload=()=>{$('#imageSkeleton').classList.add('hidden');img.classList.remove('hidden');};img.onerror=()=>{$('#imageSkeleton').classList.add('hidden');$('#imageError').classList.remove('hidden');};img.src=state.poster.imageUrl+(state.poster.imageUrl.includes('?')?'&':'?')+'r='+(Date.now()%10000);}

function renderRubric(){
 if(!state.activeRubricKey)state.activeRubricKey=RUBRIC.find(r=>!state.scores[r.key])?.key||RUBRIC[0].key;
 $('#rubricList').innerHTML=RUBRIC.map((r,i)=>{const v=state.scores[r.key],open=state.activeRubricKey===r.key;return `<section class="rubric-item ${v?'completed':''} ${open?'is-open':''}" data-key="${r.key}"><div class="rubric-top"><button type="button" class="rubric-heading" aria-expanded="${open}"><span class="rubric-title"><span class="rubric-no">${v?'✓':i+1}</span><span><strong>${r.title}</strong><small>${v?LEVELS[levelFor(v)].name+' · '+v+'/20':'Belum diisi · maksimum 20'}</small></span></span><span class="rubric-action">${open?'Tutup':v?'Ubah':'Isi'} ${open?'↑':'↓'}</span></button></div><div class="rubric-body"><div class="level-buttons">${LEVELS.map((l,li)=>`<button type="button" class="level-btn ${v>=l.range[0]&&v<=l.range[1]?'active':''}" data-level="${li}" style="--level:${l.color}">${l.name}<span>${l.range[0]}–${l.range[1]}</span></button>`).join('')}</div><div class="score-slot">${renderScoreChoices(r.key,v)}</div><p class="rubric-description">${v?escapeHtml(r.descriptions[levelFor(v)]):'Pilih tahap rubrik, kemudian pilih markah yang tepat.'}</p></div></section>`}).join('');
 $$('.rubric-heading').forEach(btn=>btn.addEventListener('click',()=>{const key=btn.closest('.rubric-item').dataset.key;state.activeRubricKey=state.activeRubricKey===key?null:key;renderRubric();}));$$('.level-btn').forEach(btn=>btn.addEventListener('click',()=>chooseLevel(btn.closest('.rubric-item').dataset.key,+btn.dataset.level)));bindScoreChoices();updateTotal();
}
function renderScoreChoices(key,v,forcedLevel){const li=forcedLevel??(v?levelFor(v):null);if(li===null)return '';const [a,b]=LEVELS[li].range;return `<div class="score-choices" aria-label="Pilih markah">${Array.from({length:b-a+1},(_,i)=>a+i).map(n=>`<button type="button" class="score-choice ${v===n?'active':''}" data-key="${key}" data-score="${n}">${n}</button>`).join('')}</div>`;}
function chooseLevel(key,li){const item=$(`.rubric-item[data-key="${key}"]`);item.querySelectorAll('.level-btn').forEach((b,i)=>b.classList.toggle('active',i===li));item.querySelector('.score-slot').innerHTML=renderScoreChoices(key,state.scores[key],li);item.querySelector('.rubric-description').textContent=RUBRIC.find(r=>r.key===key).descriptions[li];bindScoreChoices();}
function bindScoreChoices(){$$('.score-choice').forEach(b=>b.addEventListener('click',()=>{const key=b.dataset.key,index=RUBRIC.findIndex(r=>r.key===key);state.scores[key]=+b.dataset.score;saveDraft();state.activeRubricKey=RUBRIC[index+1]?.key||key;renderRubric();requestAnimationFrame(()=>scrollAfterScore(key));}));}
function scrollAfterScore(key){const index=RUBRIC.findIndex(r=>r.key===key),next=RUBRIC[index+1],target=next?$(`.rubric-item[data-key="${next.key}"]`):$('.submit-row');if(!target)return;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;target.scrollIntoView({behavior:reduced?'auto':'smooth',block:next?'center':'end'});}
function levelFor(v){return LEVELS.findIndex(l=>v>=l.range[0]&&v<=l.range[1]);}
function updateTotal(){const vals=RUBRIC.map(r=>state.scores[r.key]),total=vals.reduce((a,v)=>a+(v||0),0),complete=vals.every(v=>Number.isInteger(v));$('#floatingTotal strong').textContent=total;$('#submitBtn').disabled=!complete;$('#incompleteHint').textContent=complete?'Semua aspek lengkap. Sila semak sebelum hantar.':'Lengkapkan semua lima aspek untuk menghantar.';}

function draftKey(){return state.judge&&state.poster?`puice_draft_${state.judge.id}_${state.poster.id}`:'';}
function saveDraft(){const key=draftKey();if(key)localStorage.setItem(key,JSON.stringify({scores:state.scores,updatedAt:new Date().toISOString()}));}
function restoreDraft(){const key=draftKey();if(!key)return;try{const draft=JSON.parse(localStorage.getItem(key)||'null');if(!draft?.scores)return;RUBRIC.forEach(r=>{const v=Number(draft.scores[r.key]);if(Number.isInteger(v)&&v>=1&&v<=20)state.scores[r.key]=v;});if(Object.keys(state.scores).length)toast('Draft markah dipulihkan.');}catch{localStorage.removeItem(key);}}
function clearDraft(){const key=draftKey();if(key)localStorage.removeItem(key);}

function openConfirmation(){const p=state.poster;$('#confirmMeta').innerHTML=`<strong>${escapeHtml(state.judge.name)}</strong><br>${escapeHtml(p.id)} · ${escapeHtml(p.title)}<br>${escapeHtml(p.school)}`;$('#confirmScores').innerHTML=RUBRIC.map(r=>`<div class="confirm-score"><span>${r.title}</span><strong>${state.scores[r.key]}/20</strong></div>`).join('');const total=Object.values(state.scores).reduce((a,v)=>a+v,0);$('#confirmTotal').textContent=`${total}/100`;$('#submitStatus').textContent='';resetSaveProgress();$('#confirmSubmit').textContent='Ya, Simpan Markah';$('#confirmDialog').showModal();}
function resetSaveProgress(){clearInterval(state.saveProgressTimer);state.saveProgressTimer=null;state.saveProgressValue=0;$('#saveProgress').classList.add('hidden');$('#saveProgressBar').style.width='0%';$('#saveProgressPercent').textContent='0%';$('#saveProgressLabel').textContent='Menyediakan simpanan…';}
function setSaveProgress(value,label){state.saveProgressValue=Math.max(state.saveProgressValue,value);$('#saveProgress').classList.remove('hidden');$('#saveProgressBar').style.width=state.saveProgressValue+'%';$('#saveProgressPercent').textContent=state.saveProgressValue+'%';if(label)$('#saveProgressLabel').textContent=label;}
function startSaveProgress(){resetSaveProgress();setSaveProgress(10,'Mengesahkan markah…');state.saveProgressTimer=setInterval(()=>{const v=state.saveProgressValue;if(v>=90)return;const next=v<35?v+5:v<65?v+3:v+1;const label=next<35?'Mengesahkan markah…':next<65?'Menghubungi sistem…':next<88?'Menyimpan ke Google Sheet…':'Menunggu pengesahan Google…';setSaveProgress(Math.min(90,next),label);},360);}
async function saveScore(){const btn=$('#confirmSubmit'),previous=state.progress.total?Math.round(state.progress.completed/state.progress.total*100):0;let failed=false;if(state.pendingPosterId!==state.poster.id){state.pendingPosterId=state.poster.id;state.pendingRequestId=crypto.randomUUID();}setButtonBusy(btn,true,'Sedang menyimpan…');$('#confirmCancel').disabled=true;$('#confirmClose').disabled=true;$('#submitStatus').textContent='';startSaveProgress();try{const data=await api('saveScore',{token:state.token,posterId:state.poster.id,scores:state.scores,requestId:state.pendingRequestId},true,{onRetry:()=>setSaveProgress(72,'Sambungan perlahan, mencuba semula…')});clearInterval(state.saveProgressTimer);setSaveProgress(100,'Markah berjaya disimpan.');$('#submitStatus').textContent='✓ Simpanan disahkan oleh sistem.';clearDraft();state.pendingPosterId='';state.pendingRequestId='';toast('Markah berjaya disimpan');await wait(650);$('#confirmDialog').close();$('#posterCard').classList.add('leaving');await wait(330);$('#posterCard').classList.remove('leaving');applyDashboard(data);updateProgress(previous);requestAnimationFrame(scrollToCurrentPoster);}catch(err){failed=true;clearInterval(state.saveProgressTimer);setSaveProgress(Math.max(12,state.saveProgressValue),'Simpanan belum berjaya. Sila cuba semula.');$('#submitStatus').textContent=err.message+' Markah anda masih dikekalkan.';toast('Simpanan gagal. Sila cuba semula.');}finally{state.saveProgressTimer=null;setButtonBusy(btn,false,failed?'Cuba Semula':'Ya, Simpan Markah');$('#confirmCancel').disabled=false;$('#confirmClose').disabled=false;}}

async function switchTab(name){$$('.tab-btn').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.tab-panel').forEach(p=>p.classList.remove('active'));$('#'+name+'Tab').classList.add('active');if(name==='gallery')loadGallery();if(name==='leaderboard')loadLeaderboard();}
async function loadGallery(){const grid=$('#galleryGrid');grid.innerHTML=skeletonCards(6);try{const data=await api('gallery',{token:state.token,page:state.galleryPage,pageSize:12,status:$('#galleryStatus').value,query:$('#gallerySearch').value.trim()},true);state.galleryItems=data.items;state.galleryPages=data.pages||1;state.galleryPage=data.page;renderGallery(data);}catch(err){grid.innerHTML=`<div class="empty-state">${escapeHtml(err.message)}</div>`;}}
function renderGallery(data){const grid=$('#galleryGrid');if(!data.items.length)grid.innerHTML='<div class="empty-state">Tiada poster sepadan dengan carian ini.</div>';else grid.innerHTML=data.items.map((p,i)=>`<article class="gallery-card" data-index="${i}"><div class="gallery-img"><img src="${escapeHtml(p.thumbnailUrl)}" alt="" loading="lazy">${p.judged?'<span class="gallery-check">✓</span>':''}</div><div class="gallery-info"><small>${escapeHtml(p.id)}</small><h3>${escapeHtml(p.title)}</h3><p>${escapeHtml(p.school)}</p><div class="gallery-total"><span>${p.judged?'Telah Dinilai':'Belum Dinilai'}</span><strong>${p.judged?p.total+'/100':'–'}</strong></div></div></article>`).join('');$$('.gallery-card').forEach(c=>c.addEventListener('click',()=>openGalleryItem(data.items[+c.dataset.index])));$('#galleryPageInfo').textContent=`Halaman ${data.page} daripada ${data.pages||1}`;$('#galleryPrev').disabled=data.page<=1;$('#galleryNext').disabled=data.page>=data.pages;}
function openGalleryItem(p){openPosterModal(p);if(p.judged)$('#posterModalInfo').innerHTML+=`<div class="confirm-scores">${RUBRIC.map(r=>`<div class="confirm-score"><span>${r.title}</span><strong>${p.scores[r.key]}/20</strong></div>`).join('')}</div><p>Jumlah: <strong>${p.total}/100</strong> · Disimpan ${formatDate(p.updatedAt)}</p>`;}
function openPosterModal(p){resetPosterZoom();$('#posterModalImage').src=p.imageUrl;$('#posterModalInfo').innerHTML=`<strong>${escapeHtml(p.id)} · ${escapeHtml(p.title)}</strong><br><small>${escapeHtml(p.school)}</small>`;$('#posterDialog').showModal();}

function setPosterZoom(scale,x=state.zoomX,y=state.zoomY){state.zoomScale=Math.min(4,Math.max(1,scale));state.zoomX=state.zoomScale===1?0:x;state.zoomY=state.zoomScale===1?0:y;$('#posterModalImage').style.transform=`translate(${state.zoomX}px,${state.zoomY}px) scale(${state.zoomScale})`;$('#posterZoomReset').textContent=Math.round(state.zoomScale*100)+'%';}
function resetPosterZoom(){setPosterZoom(1,0,0);}
function bindPosterZoom(){const viewport=$('#posterZoomViewport');$('#posterZoomIn').addEventListener('click',()=>setPosterZoom(state.zoomScale+.5));$('#posterZoomOut').addEventListener('click',()=>setPosterZoom(state.zoomScale-.5));$('#posterZoomReset').addEventListener('click',resetPosterZoom);viewport.addEventListener('dblclick',()=>setPosterZoom(state.zoomScale>1?1:2.25,0,0));viewport.addEventListener('wheel',e=>{e.preventDefault();setPosterZoom(state.zoomScale+(e.deltaY<0?.25:-.25));},{passive:false});viewport.addEventListener('pointerdown',e=>{viewport.setPointerCapture(e.pointerId);state.zoomPointers.set(e.pointerId,{x:e.clientX,y:e.clientY});});viewport.addEventListener('pointermove',e=>{if(!state.zoomPointers.has(e.pointerId))return;e.preventDefault();const previous=state.zoomPointers.get(e.pointerId);state.zoomPointers.set(e.pointerId,{x:e.clientX,y:e.clientY});const points=[...state.zoomPointers.values()];if(points.length===2){const distance=Math.hypot(points[0].x-points[1].x,points[0].y-points[1].y);if(!state.zoomStartDistance){state.zoomStartDistance=distance;state.zoomStartScale=state.zoomScale;}setPosterZoom(state.zoomStartScale*(distance/state.zoomStartDistance));}else if(state.zoomScale>1){setPosterZoom(state.zoomScale,state.zoomX+e.clientX-previous.x,state.zoomY+e.clientY-previous.y);}},{passive:false});const end=e=>{state.zoomPointers.delete(e.pointerId);if(state.zoomPointers.size<2)state.zoomStartDistance=0;};viewport.addEventListener('pointerup',end);viewport.addEventListener('pointercancel',end);}

async function loadLeaderboard(){await loadLeaderboardInto($('#leaderboardContent'),'leaderboard',{token:state.token});}
async function openAdminResults(){if(state.adminToken){showScreen('adminResults');await loadAdminLeaderboard();return;}$('#adminPinInput').value='';$('#adminPinError').textContent='';$('#adminPinDialog').showModal();setTimeout(()=>$('#adminPinInput').focus(),100);}
async function adminLogin(){const pin=$('#adminPinInput').value.trim();if(!/^\d{6}$/.test(pin)){return $('#adminPinError').textContent='Masukkan PIN urusetia enam digit yang sah.';}setButtonBusy($('#adminPinSubmit'),true,'Mengesahkan…');$('#adminPinError').textContent='';try{const data=await api('adminLogin',{pin},true);state.adminToken=data.token;sessionStorage.setItem('puice_admin_token',state.adminToken);$('#adminPinDialog').close();showScreen('adminResults');await loadAdminLeaderboard();}catch(err){$('#adminPinError').textContent=err.message;}finally{setButtonBusy($('#adminPinSubmit'),false,'Buka Keputusan');}}
async function loadAdminLeaderboard(){await loadLeaderboardInto($('#adminLeaderboardContent'),'adminLeaderboard',{token:state.adminToken});}
async function loadLeaderboardInto(box,action,payload){box.innerHTML='<div class="leaderboard-lock">Menyemak status keseluruhan penjurian…</div>';try{const data=await api(action,payload,true);if(!data.complete){box.innerHTML=`<div class="leaderboard-lock"><div class="completion-icon" style="background:#eef2f7;color:#10233f">⌛</div><h3>Penghakiman belum lengkap</h3><p>Keputusan akan dipaparkan selepas ketiga-tiga hakim selesai menilai semua poster.</p><div class="judge-progress-list">${data.judges.map((j,i)=>{const pct=j.total?Math.round(j.completed/j.total*100):0;return `<div class="judge-progress-item"><div><strong>Hakim ${i+1}</strong><span>${j.completed}/${j.total}</span></div><div class="mini-progress"><span style="width:${pct}%;background:${COLORS[i]}"></span></div></div>`}).join('')}</div></div>`;return;}renderLeaderboard(data.items,box);}catch(err){box.innerHTML=`<div class="leaderboard-lock">${escapeHtml(err.message)}</div>`;}}
function renderLeaderboard(items,box=$('#leaderboardContent')){const groups=[['Platinum','#5364d8'],['Emas','#d9a520'],['Perak','#7b8799'],['Gangsa','#a96c42'],['Tiada Anugerah','#5f6671']];box.innerHTML=groups.map(([name,color])=>{const rows=items.filter(x=>x.award===name);if(!rows.length)return '';return `<section class="award-section" style="--award:${color}"><div class="award-banner">${name} · ${rows.length} penerima</div><table class="ranking-table"><thead><tr><th>#</th><th>ID</th><th>Peserta / Poster / Sekolah</th><th>Hakim 1</th><th>Hakim 2</th><th>Hakim 3</th><th>Jumlah</th></tr></thead><tbody>${rows.map(r=>`<tr><td data-label="Kedudukan">${r.rank}</td><td data-label="ID Poster">${escapeHtml(r.id)}</td><td data-label="Peserta / Poster / Sekolah"><strong>${escapeHtml(r.participant||'—')}</strong><br>${escapeHtml(r.title)}<br><small>${escapeHtml(r.school)}</small></td>${r.judgeTotals.map((s,i)=>`<td data-label="Hakim ${i+1}">${s}</td>`).join('')}<td data-label="Jumlah"><strong>${r.total}/300</strong></td></tr>`).join('')}</tbody></table></section>`}).join('');}

function setButtonBusy(btn,busy,text){btn.disabled=busy;btn.dataset.original=btn.dataset.original||btn.textContent;btn.textContent=busy?text:(text||btn.dataset.original);}
function initials(name){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function formatDate(v){if(!v)return 'belum tersedia';const d=new Date(v);return Number.isNaN(d.getTime())?v:new Intl.DateTimeFormat('ms-MY',{dateStyle:'medium',timeStyle:'short'}).format(d);}
function wait(ms){return new Promise(r=>setTimeout(r,ms));}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600);}
function confetti(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const c=$('#confetti'),colors=['#2458e6','#4bc6e6','#f4bb4a','#13a77a','#ef5d64'];for(let i=0;i<34;i++){const e=document.createElement('i');e.style.left=Math.random()*100+'vw';e.style.setProperty('--x',(Math.random()*180-90)+'px');e.style.setProperty('--c',colors[i%colors.length]);e.style.animationDelay=Math.random()*.45+'s';c.appendChild(e);setTimeout(()=>e.remove(),2400);}}
function skeletonCards(n){return Array.from({length:n},()=>'<div class="gallery-card"><div class="gallery-img image-skeleton"></div><div class="gallery-info"><h3>Memuatkan…</h3></div></div>').join('');}

const MOCK_JUDGES=[['H01','SITI HIDAYU BINTI LUDIN'],['H02','Khamizah binti Kamarudin'],['H03','Mohd Muhaimin bin Che Mansor']];
const MOCK_POSTERS=[
 {id:'P001',title:'Poster Digital 1',school:'Sekolah Contoh 1',category:'Terbuka',imageUrl:'https://drive.google.com/thumbnail?id=1CPX1GEgSKbqvozIWDhctNiXC3cabaLbN&sz=w1600',thumbnailUrl:'https://drive.google.com/thumbnail?id=1CPX1GEgSKbqvozIWDhctNiXC3cabaLbN&sz=w600'},
 {id:'P002',title:'Poster Digital 2 dengan Tajuk yang Lebih Panjang',school:'Sekolah Kebangsaan Contoh dengan Nama Sangat Panjang',category:'Terbuka',imageUrl:'https://drive.google.com/thumbnail?id=1q9n6D7zkn2BJHn6R4JxdvuEzpbHheT0W&sz=w1600',thumbnailUrl:'https://drive.google.com/thumbnail?id=1q9n6D7zkn2BJHn6R4JxdvuEzpbHheT0W&sz=w600'},
 {id:'P003',title:'Poster Digital 3',school:'Sekolah Contoh 3',category:'Terbuka',imageUrl:'https://drive.google.com/thumbnail?id=1UPowuwWolILsdzELk4XAV-yMhEZF3_cD&sz=w1600',thumbnailUrl:'https://drive.google.com/thumbnail?id=1UPowuwWolILsdzELk4XAV-yMhEZF3_cD&sz=w600'}
];
async function mockApi(action,payload){await wait(180);const jid=payload.token||localStorage.getItem('mock_judge')||'H01',scores=JSON.parse(localStorage.getItem('mock_scores')||'{}'),judge=MOCK_JUDGES.find(j=>j[0]===jid)||MOCK_JUDGES[0],mine=scores[judge[0]]||{};if(action==='bootstrap')return{judges:MOCK_JUDGES.map(j=>({id:j[0],name:j[1],completed:Object.keys(scores[j[0]]||{}).length,total:3}))};if(action==='login'){localStorage.setItem('mock_judge',payload.judgeId);const token=payload.judgeId,dashboard=await mockApi('dashboard',{token:token});return{token:token,judge:{id:payload.judgeId,name:(MOCK_JUDGES.find(j=>j[0]===payload.judgeId)||[])[1]},dashboard:dashboard};}if(action==='adminLogin')return{token:'mock-admin'};if(action==='dashboard'){const remaining=MOCK_POSTERS.filter(p=>!mine[p.id]);return{judge:{id:judge[0],name:judge[1]},poster:remaining[0]||null,nextPoster:remaining[1]||null,progress:{completed:Object.keys(mine).length,total:3},lastUpdated:new Date()};}if(action==='saveScore'){scores[judge[0]]=scores[judge[0]]||{};scores[judge[0]][payload.posterId]={scores:payload.scores,total:Object.values(payload.scores).reduce((a,b)=>a+b,0),updatedAt:new Date().toISOString()};localStorage.setItem('mock_scores',JSON.stringify(scores));return mockApi('dashboard',{token:judge[0]});}if(action==='gallery'){let items=MOCK_POSTERS.map(p=>({...p,judged:!!mine[p.id],...(mine[p.id]||{})}));if(payload.status==='judged')items=items.filter(x=>x.judged);if(payload.status==='unjudged')items=items.filter(x=>!x.judged);const q=String(payload.query||'').toLowerCase();if(q)items=items.filter(x=>(x.title+' '+x.school).toLowerCase().includes(q));return{items,page:1,pages:1,categories:['Terbuka']};}if(action==='leaderboard'||action==='adminLeaderboard')return{complete:false,judges:MOCK_JUDGES.map(j=>({completed:Object.keys(scores[j[0]]||{}).length,total:3}))};throw new Error('Mock action tidak dikenali.');}
